/// This file is automatically generated. Any changes will be overwritten.

import Foundation

public enum LocalizedKey: String, CaseIterable {

  // Base localization: "Well, that's why we have tests."
  case does_this_work

  // Base localization: "Oh stop being so sanctimonious."
  case o_rly

  public var localizedValue: String {
    NSLocalizedString(self.rawValue,
                      bundle: .module,
                      comment: "")
  }
}
